#Workflow for GitHub Actions

name: i2util-workflow
  
on:  
  workflow_dispatch:
    inputs:  
      OS: 
        description: 'OS to build'
        required: true
      BUILD_VARS_JSON:
        description: 'Build var json file'
        required: true
  workflow_run:
    workflows: "Create Artifacts and pass runid"
    branches: 'github-workflow'
    types:
      - completed

jobs:
       
  build-i2util:

     runs-on: ubuntu-latest
     
     steps:
        - name: Check out Repo
          uses: actions/checkout@v4
          with:
           ref: 5.2.0
           
        - name: Use BUILD_VARS_JSON
          run: |
            echo "BUILD_VARS_JSON value is: ${{ env.BUILD_VARS_JSON }}"
            echo "BUILD_VARS_JSON=${BUILD_VARS_JSON}"

        - name: Verify BUILD_VARS_JSON
          run: |
            echo "Printing BUILD_VARS_JSON for verification"
            echo " **** next ****"
            echo "${{ github.event.inputs.BUILD_VARS_JSON }}"
            echo " **** next next ****"
            echo "${{ fromJson(github.event.inputs.BUILD_VARS_JSON) }}"    

       # - name: update build_vars.json
       #   run: |
       #     echo "jq print the file  ***********************"
       #     jq . "${{ env.BUILD_VARS_JSON }}"



            
      #  - name: Create a temporary artifact downloads folder
      #    run: mkdir aritfacts

      #  - name: run docker oneshot builder
      #    run: |
      #     curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - . '${{ github.event.inputs.OS }}'  

      #  - uses: actions/upload-artifact@v3
      #    with:
      #    #Name the artifact uniquely
      #      name: ${{ github.event.repository.name }}-${{ github.event.inputs.OS }}
      #      #Where the finished product lives after the build
      #      path: unibuild-repo
      #      #Don't keep these for long.  This is just a test.
      #      retention-days: 5
      #   
      #  - name: Pass workflow to owamp repo
      #    uses: actions/github-script@v6
      #    with:
      #      github-token: ${{ secrets.GIT_ACTIONS }}
      #      script: |
      #        await github.rest.actions.createWorkflowDispatch({
      #        owner: 'cs1867',
      #        repo: 'owamp',
      #        workflow_id: 'owamp-workflow.yml',
      #        ref: 'github-workflow',
      #         inputs: {
      #          OS:  '${{ github.event.inputs.OS }}',
      #          MINORPACKAGEID:  '${{ github.event.inputs.MINORPACKAGEID }}',
      #          I2UTILID: '${{ github.run_id }}'
      #        }
      #        })
    
