#Workflow for GitHub Actions

name: i2util-workflow
  
on:  
  workflow_dispatch:
    inputs: 
      OS: 
        description: 'OS to build'
        required: true
      MINORPACKAGEID:
        description: 'Minor Package run id'
        required: true
  workflow_run:
    workflows: "Create Artifacts and pass runid"
    branches: 'github-docker'
    types:
      - completed

jobs:
       
  build-i2util:

     runs-on: ubuntu-latest
     
     steps:
        - name: Check out Repo
          uses: actions/checkout@v4
          with:
           ref: 5.2.0
          
        - name: Create a temporary artifact downloads folder
          run: mkdir aritfacts

        - name: run docker oneshot builder
          run: |
           curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - . '${{ github.event.inputs.OS }}'  

        - uses: actions/upload-artifact@v3
          with:
          #Name the artifact uniquely
            name: ${{ github.event.repository.name }}-${{ github.event.inputs.OS }}
            #Where the finished product lives after the build
            path: unibuild-repo
            #Don't keep these for long.  This is just a test.
            retention-days: 5
         
        - name: Pass workflow 
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GIT_ACTIONS }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
              owner: 'cs1867',
              repo: 'owamp',
              workflow_id: 'owamp-docker.yml',
              ref: 'github-docker',
               inputs: {
                OS:  '${{ github.event.inputs.OS }}',
                MINORPACKAGEID:  '${{ github.event.inputs.MINORPACKAGEID }}',
                I2UTILID: '${{ github.run_id }}'
              }
              })
    
